### PR TITLE
Sindarin Refactoring

### LINKED ISSUE #29: There are many duplicate helper methods in `SindarinDebuggerTest` with unexplicit names
`SindarinDebuggerTest` has a lot of `helperMethodXXX` methods.

Actuallly, most of these methods have the same source code:

image

Out of the 29 helper methods from this class, 15 of them have the exact same source code. Only one from these 15 should be kept and the others should be deleted.

Plus, all these methods should have a more explicit name as, when I try to understand a test, it forces me to browse the helper method that is used in the test because it doesn't have an explicit name.

### PR DESCRIPTION
**Pull request by adri09070**
Fixes #29

w/ @StevenCostiou 

- removing and cleaning VirtualBreakpoint and stepHooks  as they were unused
- cleaning duplicate helper methods
- cleaning useless helper methods and changing tests to use the lowest possible number of helper methods
- giving explicit names to helper methods
- removing all `self skipOnPharoCITestingEnvironment` in tests as all tests are green

### CODE REVIEW

**Comment by StevenCostiou** [comment]
There are conflicts it seems?

**Comment by adri09070** [comment]
Yes, there was  big synchronization problem because the `Pharo-11` branch wasn't up to date with the master branch: https://github.com/pharo-spec/ScriptableDebugger/pull/59

**Comment by adri09070** [comment]
Failing test is unrelated (still zinc-related)

**Comment by StevenCostiou** [comment]
I'm re-running the job with the unrelated failing test to see if everything passes.
Then if it is still there, as everything is green we'll try a merge.

**Pull request merged**
