### PR TITLE
compiling missing method when loading master or Pharo12 in P12, because it deletes a method from the entire system, while it should ONLY delete it from Sindarin

### PR DESCRIPTION
**Pull request by adri09070**
consequence of: https://github.com/pharo-spec/ScriptableDebugger/pull/65 and fixes https://github.com/pharo-spec/NewTools/issues/538

### CODE REVIEW

**Comment by adri09070** [comment]
Unrelated failing tests

**Comment by MarcusDenker** [comment]
is this really a good idea to compile that method on the fly?

**Comment by MarcusDenker** [comment]
e.g. we could just backport it to Pharo10

**Comment by adri09070** [comment]
I don't really know, I don't really like the idea but the only other solution was to load a package that contains only this method, that would be loaded only for Pharo12. But this looks too extreme for only one method.

If you have a better solution, I'll go for it. I don't really see what you mean by "backport it"

**Comment by MarcusDenker** [comment]
Ah, I think I misunderstood. Yes, this is the simplest solution for now to compile the method

**Comment by StevenCostiou** [comment]
The failing test seems to not come from here.
@adri09070could you have a look?

**Comment by adri09070** [comment]
> The failing test seems to not come from here. @adri09070could you have a look?

Yes, this is ok

**Comment by StevenCostiou** [comment]
unrelated failure

**Pull request merged**
